### ISSUE TITLE
Open source archive for build 17.1.2.A.0.314

### ISSUE THREAD

**Issue by AndroPlus-org** [sonyxperiadev/kernel-copyleft#1]
Hello,
I can't find open source archive for Xperia Z2 17.1.2.A.0.314, which is released on 2014-07-18.
Could you commit source for build 17.1.2.A.0.314 on Github?
Thank you.

**Comment by DooMLoRD** [comment]
Agreed with @WedyDQ10 !

There are no sources of msm8974ab for the firmware range: 17.1.2.A.0.xxx

PTCRB lists atleast 2 versions in this range: https://www.ptcrb.com/vendor/complete/view_complete_request_guest.cfm?modelid=24754

@sonyxperiadev , @andersson & @jerpelea 
please release the sources at the earliest!

Thanks!

regards,
DooMLoRD
