### ISSUE TITLE
Xperia Z1 compact 

### ISSUE THREAD

**Issue by ghost** [sonyxperiadev/kernel-copyleft#11]
Hello,
I can't found the rhine_amami_row_defconfig! Which config shoud I use for Xperia Z1 compact?
Thank you.

**Comment by jerpelea** [comment]
in each branch you can find a Readme file that explains howto build the kernel and which devices are supported

**Comment by ghost** [comment]
Thank you!

**Comment by msaw** [comment]
I followed the instructions described in https://developer.sonymobile.com/2014/08/28/how-to-rebuild-kernels-for-flagship-xperia-devices-tutorial/ but when I built the boot.img with the command:
`$ /mkqcdtbootimg --kernel $(KERNEL_SRC_PATH)/arch/arm/boot/zImage --ramdisk ramdisk.cpio.gz --base 0x00000000 --ramdisk_offset 0x02000000 --tags_offset 0x01E00000 --pagesize 2048 --cmdline "androidboot.hardware=qcom user_debug=31 maxcpus=2 msm_rtb.filter=0x3F ehci-hcd.park=3 msm_rtb.enable=0 lpj=192598 dwc3.maximum_speed=high dwc3_msm.prop_chg_detect=Y" --dt_dir $(KERNEL_SRC_PATH)/arch/arm/boot/ -o boot.img`
The phone doesnt boot! 
PS: I use the branch 14.6.A.0.xxx
