### ISSUE TITLE
Missing archive for 18.1.A.1.xx (xperia T3)

### ISSUE THREAD

**Issue by MayeulC** [sonyxperiadev/kernel-copyleft#13]
Hello there,
This repository doesn't seem to contain the sources for the Xperia T3, especially the 18.1.A.1.xx version.
Would it be possible to add them? They were originally published [here](https://developer.sonymobile.com/downloads/xperia-open-source-archives/open-source-archive-for-build-18-1-a-1-23/).

**Comment by jerpelea** [comment]
unfortunately Xperia T3 is released only as a zip
