### ISSUE TITLE
No update?

### ISSUE THREAD

**Issue by AndroPlus-org** [sonyxperiadev/kernel-copyleft#14]
There are no updates after 41.2.A.0.xxx.
Is this project abandoned?
Is Sony not interested in open source development for Sony ROM?

**Comment by jerpelea** [comment]
there will be new copylefts soon

**Comment by jerpelea** [comment]
oue Open Devices is active and you can find information on our new website
https://developer.sony.com/develop/open-devices/

**Comment by jerpelea** [comment]
there will be new copylefts soon
