### ISSUE TITLE
Branch names ?

### ISSUE THREAD

**Issue by warraagal** [sonyxperiadev/kernel-copyleft#15]
Can someone please point me to an explanation of the branch naming convention. For example what does 14.1.B.0.xxx mean ?

**Comment by zachariasmaladroit** [comment]
@r4rounak if you own the matching Xperia device you'll probably see similarities in the branch name vs. recent firmware update

e.g.

https://github.com/sonyxperiadev/kernel-copyleft/commits/34.4.A.0.xxx

matches with http://www.xperiablog.net/2018/02/05/android-oreo-rolls-out-to-xperia-x-and-x-compact-34-4-a-0-364/  **34.4.A.0.** 364


so in your case 14.1.B.0.xxx would be a kernel branch for the Xperia Z Ultra device

http://www.xperiablog.net/2013/08/02/xperia-z-ultra-gets-its-first-firmware-update-14-1-b-0-471/

**Comment by warraagal** [comment]
Thank you. I understand now.
