### ISSUE TITLE
release for 33.2.A.3.81

### ISSUE THREAD

**Issue by hermesthecat** [sonyxperiadev/kernel-copyleft#16]
can you relase Sony xperia XA F3111  33.2.A.3.81 ?

**Comment by bartcubbins** [comment]
https://developer.sony.com/file/download/open-source-archive-for-33-2-a-3-81-33-2-b-3-81/
https://developer.sony.com/file/download/open-source-archive-for-33-2-a-4-72-and-33-2-b-4-72/
