### ISSUE TITLE
Missing sources

### ISSUE THREAD

**Issue by pantherale0** [sonyxperiadev/kernel-copyleft#17]
Hi,

Could you release source code for F3311/F3313 please?

Latest version is: 37.0.A.2.252

Thanks

**Comment by jerpelea** [comment]
the latest copylefts can be found on our webpage 
https://developer.sony.com/develop/open-devices/downloads/open-source-archives

**Comment by pantherale0** [comment]
Hi,

I've already checked here. Version 37.0.A.2.152 is available however the version above isn't

**Comment by jerpelea** [comment]
@11harveyj the copyleft was released on DW. Thans for your patience
