### ISSUE TITLE
Kernel built boots but no touchscreen or other drivers available

### ISSUE THREAD

**Issue by Jimbo77** [sonyxperiadev/kernel-copyleft#18]
Hello!

I have successfully compiled Image, dtb.img and dtbo.img from sources on branch  61.0.A.11.xx for PDX215, however touchscreen does not work upon boot. I am assuming this is because of needed modules missing on build, however there is no way to build the modules along with the kernel only. As per my understanding the kernel-modules makefile requires this to be part of a more complex build process like AOSP or similiar.

I will be awesome if these could be instead included in the source and added to the defconfig files. Or can you instruct on how to build these modules to successfully load them with the new boot image?

**Comment by jerpelea** [comment]
hello 
the touch screen module driver is located in vendor and can be compiled as a module . you can integrate it in the kernel code and build them together or compile the code separate
