### ISSUE TITLE
Kernel source code for Xperia 1 ii

### ISSUE THREAD

**Issue by hellobbn** [sonyxperiadev/kernel-copyleft#20]
Hi, can you release the kernel source code for Xperia 1 ii? It has not been updated since April 2021. Specifically, for version 58.1.A.5.530 or 58.2.A.2.90.

**Comment by hellobbn** [comment]
Bumping this, sony has not released kernel source for Xperia 1 II Android 12 (58.2.A.7.55 or later). Which is a [GPL violation](https://www.gnu.org/licenses/gpl-violation.en.html)

**Comment by jerpelea** [comment]
@hellobbn we are working on the situation and we will release the kernel sources ASAP

**Comment by jerpelea** [comment]
@hellobbn,
 
Thank you for raising awareness around the publication of our software.
 
We investigated and confirmed that the disclosure has been omitted for Copyleft Archive for Xperia 1 II Android 12, as you pointed out.
Copyleft Archive of "58.2.A.7.55" will be published June 29th and we expect publication of the remaining Copyleft Archive of Xperia 1II in due course. 
You can find these our Developer World site.

**Comment by hellobbn** [comment]
@jerpelea Thanks for that. Do you have plan to release dts files for the corresponding kernel source code?

**Comment by jerpelea** [comment]
@hellobbn 

Thank you for raising awareness around the publication of our software.
We will release dts files soon after Copyleft Archive release.

**Comment by jerpelea** [comment]
@hellobbn 

The copylef archive and matching dts are released 
Thank you for raising awareness around the publication of our software.
