### ISSUE TITLE
[pdx203] Not able to boot kernel source 58.2.A.7.55

### ISSUE THREAD

**Issue by hellobbn** [sonyxperiadev/kernel-copyleft#22]
Hi,
  I am not able to boot the kernel compiled from copyleft source 58.2.A.7.55, the drm has the following errors:

```
03-15 16:52:24.021     0     0 W         : dsc 2 not peer of dsc 1
03-15 16:52:24.021     0     0 E         : [drm:_sde_rm_reserve_dsc] [sde error]couldn't reserve 2 dsc blocks for enc id 28
03-15 16:52:24.021     0     0 E         : [drm:sde_rm_reserve] [sde error]failed to reserve hw resources: -22, test_only 0
03-15 16:52:24.021     0     0 E         : [drm:sde_encoder_update_caps_for_cont_splash:6102] [sde error]enc28 failed to reserve hw resources, -22

```

**Comment by hellobbn** [comment]
The provided copyleft dts files, specifically, in the qcom folder, are incorrect, which leads to this problem.

**Comment by jerpelea** [comment]
@hellobbn I willl double check the dts release

**Comment by hellobbn** [comment]
@jerpelea The commit linked below fixed the proble, and I think this line leads to the problem: https://github.com/hellobbn/android_kernel_sony_sm8250/commit/62423c85f4bc03964b0bf0d19319c2ed4e3a0e4f#diff-634ad704dac15d515b50ff5d99dca599b9f102db798e2ad450db7ba4f156f597R99

**Comment by jerpelea** [comment]
@hellobbn the dts seems to be in sync with the release
I am glad that you fixed the reported issue

**Comment by hellobbn** [comment]
The compiled dt.img and dtbo.img are not the same as the stock one, and lacks a lot of entries, so I still think there are problems with the dts release.

But since those problems have been addressed, I have no further questions ^ ^
