### ISSUE TITLE
Archive for 18.5.c.0.19 ? (E3)

### ISSUE THREAD

**Issue by tormath1** [sonyxperiadev/kernel-copyleft#23]
Hello, I'm looking for this archive and I did not find it on this repo nor on this page: https://developer.sony.com/develop/open-devices/downloads/open-source-archives/

Any chance to have it somewhere else?

**Comment by jerpelea** [comment]
HI 
let me check and I will get back to you 
Best regards
Alin

**Comment by tormath1** [comment]
Hello,

It look like 18.5.c.0.25 is now available: https://developer.sony.com/file/download/open-source-archive-for-18-5-c-0-25 which should be OK.

Thanks!
