### ISSUE TITLE
Request kernel source for 67.0.A.4.22

### ISSUE THREAD

**Issue by hellobbn** [sonyxperiadev/kernel-copyleft#24]
Hi, are there any plans to release kernel/dts sources for Xperia 1 V, version 67.0.A.4.22?

**Comment by jerpelea** [comment]
it will be released soon

**Comment by jerpelea** [comment]
The first copyleft for Xperia 1V is released as an archive. 
https://developer.sony.com/file/download/open-source-archive-for-67-0-a-1-127

**Comment by jerpelea** [comment]
kernel and device tree was pushed to github

**Comment by hellobbn** [comment]
Hi, it seems the `audio-kernel` is missing from the copyleft release.
See _yodo-1.0.0/copyleft-publications/vendor/qcom/opensource_ there is no `audio-kernel`

**Comment by jerpelea** [comment]
we are investigating it and will be released ASAP

**Comment by hellobbn** [comment]
Please also check display-drivers, thanks!

**Comment by hellobbn** [comment]
Hi, is there any progress on the missing files?

**Comment by jerpelea** [comment]
Hi 
thanks for the reminder
They are WIP and will be released ASAP
Best regards
Alin
