### ISSUE TITLE
release for 58.2.A.10.44

### ISSUE THREAD

**Issue by kkze** [sonyxperiadev/kernel-copyleft#26]
I can't find the version and the link below doesn't work to download the file.
https://developer.sony.com/file/download/open-source-archive-for-58-2-a-10-44
I really need it, please help!

**Comment by jerpelea** [comment]
Hello 
thanks for reaching us 
The download link will be fixed ASAP

Best regards
Alin

**Comment by jerpelea** [comment]
The issue has been fixed
Thanks for reporting it
