### ISSUE TITLE
[HELP] 58.1.A.1xxx

### ISSUE THREAD

**Issue by youngxiaoloong** [sonyxperiadev/kernel-copyleft#27]
This happens at compile time
`  CC      net/wireless/nl80211.o`
`../drivers/mmc/core/host.c:710:46: error: use of undeclared identifier 'dev_attr_perf'`
`        err = device_create_file(&host->class_dev, &dev_attr_perf);`
`                                                    ^`
`../drivers/mmc/core/host.c:756:40: error: use of undeclared identifier 'dev_attr_perf'`
`        device_remove_file(&host->class_dev, &dev_attr_perf);`
`                                             ^`
`2 errors generated.`
`make[4]: *** [../scripts/Makefile.build:338: drivers/mmc/core/host.o] Error 1`
`make[3]: *** [../scripts/Makefile.build:642: drivers/mmc/core] Error 2`
`make[2]: *** [../scripts/Makefile.build:642: drivers/mmc] Error 2`
`make[2]: *** Waiting for unfinished jobs....`

**Comment by youngxiaoloong** [comment]
How can i fix it?

**Comment by jerpelea** [comment]
I would guess that you miss something in .config
Best regards
Alin
