### ISSUE TITLE
Request kernel source for 67.1.A.2.220

### ISSUE THREAD

**Issue by hellobbn** [sonyxperiadev/kernel-copyleft#28]
Hi, the kernel source for Xperia 1 V Android 14 has not been released yet.

**Comment by jerpelea** [comment]
Hello
unfortunately not yet but we are working on it 
Best regards
Alin

**Comment by jerpelea** [comment]
Hi @hellobbn 
sorry for the delay 
the copyleft is published 
https://developerworld.wpp.developer.sony.com/file/download/open-source-archive-for-67-1-a-2-220
Best regards
Alin
