### ISSUE TITLE
unable to bind to client socket, rc = -1 errno[13:Permission denied]

### ISSUE THREAD

**Issue by switchgott** [sonyxperiadev/kernel-copyleft#5]
Hi,
i compiled kernel source for sony pollux (tablet z with 3g).
Kernel boots into stock 5.1.1.
But i get a reboot every 2 minutes.
I get this error...
D/QC-QMI ( 696): using socket paths bind=/dev/socket/qmux_radio/qmux_client_socket, connect=/dev/socket/qmux_radio/qmux_connect_socket
E/QC-QMI ( 696): qmi_client [696]: unable to bind to client socket, rc = -1 errno[13:Permission denied]
D/QC-QMI ( 655): using socket paths bind=/dev/socket/qmux_radio/qmux_client_socket, connect=/dev/socket/qmux_radio/qmux_connect_socket
E/QC-QMI ( 655): qmi_client [655]: unable to connect to server, errno=[2:No such file or directory], attempt=1

Seems that the 3g modem could not start right.
With stock kernel, no problem..
Any idea?
Thanks....

**Comment by bartcubbins** [comment]
@jerpelea outdated. can be closed
