### ISSUE TITLE
Xperia X: which is the defconfig?

### ISSUE THREAD

**Issue by HostZero** [sonyxperiadev/kernel-copyleft#9]
Hey,

I have seen Xperia X Kernel Sources are out at 34.0.A.2.xxx

I have seen commits in "common_diffconfig" "msm_defconfig"  "msm-perf_defconfig"

so which defconfig must i use?

**Comment by ItzLevvie** [comment]
If you're wanting to build the kernel, then you should've read the ```README_Xperia``` file.

**Comment by bartcubbins** [comment]
@jerpelea the answer to the question was given. can be closed
